spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    baseline-version: 1
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: bG9jYWwtZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS0yNTYtYml0cy1sb25n
  expiration: 1209600000
#  expiration: 60000
